### ISSUE TITLE
Search field function non working in TechDocs

### ISSUE THREAD

**Issue by chantallengua** [RedHatQuickCourses/devhub-build#14] opened 2024-03-21 11:31 UTC
Hello, at the page [TechDocs and Search](https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/techdocs.html), last point (9.), even if I enter a word like "lorem" (or others) in the Search button,  I get the message "No result found" [screenshot attached]
![Screenshot from 2024-03-21 12-28-08](https://github.com/RedHatQuickCourses/devhub-build/assets/43709607/28b91aa1-1713-4349-8ddc-ed70da6b59c6)
Looking at the logs of the Developer Hub pod, I receive this error message [screenshot attached]: " backstage error Request failed with status 500 Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation. type=errorHandler cause=undefined name=MissingIndexError stack=MissingIndexError: Missing index for techdocs. This could be because the index hasn't been created yet or there was a problem during index creation."
![Screenshot from 2024-03-21 12-29-41](https://github.com/RedHatQuickCourses/devhub-build/assets/43709607/9711fd3b-3bc6-4aed-94b2-fb7adb2dc043)

**Comment by rsriniva** [comment] 2024-04-03 11:30
thanks for reporting this @chantallengua - can you please post your app-config yaml snippet for techdocs?

**Comment by rsriniva** [comment] 2024-04-04 14:50
@chantallengua - that github link is access denied for me. is it a private repo?

**Comment by rsriniva** [comment] 2024-07-18 10:07
@chantallengua - I just updated the course content to RHDH 1.2.1 and I tested this again. It is working for me as written. I am going to close this as unable to reproduce/wontfix. Please open a new issue if it does not work for you on 1.2.1

**Closed by rsriniva** 2024-07-18 10:07 UTC
Labels: wontfix

**Comment by chantallengua** [comment] 2024-07-18 12:19
Thank you, you can close it.
Have a good day

Chantal Lengua

Jr. Specialist Solution Architect

Red Hat Italy <https://www.redhat.com/>

Via Gustavo Fara 26 - 20124 Milano - ITALY
***@***.***
<https://www.redhat.com/>
